/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdLaunchRouteImport } from './routes/projects.$projectId.launch'
import { Route as ProjectsProjectIdChaptersChapterIdRouteImport } from './routes/projects.$projectId.chapters.$chapterId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdLaunchRoute = ProjectsProjectIdLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdChaptersChapterIdRoute =
  ProjectsProjectIdChaptersChapterIdRouteImport.update({
    id: '/chapters/$chapterId',
    path: '/chapters/$chapterId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/scout': typeof ScoutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/launch': typeof ProjectsProjectIdLaunchRoute
  '/projects/$projectId/chapters/$chapterId': typeof ProjectsProjectIdChaptersChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/scout': typeof ScoutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/launch': typeof ProjectsProjectIdLaunchRoute
  '/projects/$projectId/chapters/$chapterId': typeof ProjectsProjectIdChaptersChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/scout': typeof ScoutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/launch': typeof ProjectsProjectIdLaunchRoute
  '/projects/$projectId/chapters/$chapterId': typeof ProjectsProjectIdChaptersChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/scout'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId'
    | '/projects/$projectId/launch'
    | '/projects/$projectId/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/scout'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId'
    | '/projects/$projectId/launch'
    | '/projects/$projectId/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/scout'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId'
    | '/projects/$projectId/launch'
    | '/projects/$projectId/chapters/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  ScoutRoute: typeof ScoutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/launch': {
      id: '/projects/$projectId/launch'
      path: '/launch'
      fullPath: '/projects/$projectId/launch'
      preLoaderRoute: typeof ProjectsProjectIdLaunchRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/chapters/$chapterId': {
      id: '/projects/$projectId/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/projects/$projectId/chapters/$chapterId'
      preLoaderRoute: typeof ProjectsProjectIdChaptersChapterIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdLaunchRoute: typeof ProjectsProjectIdLaunchRoute
  ProjectsProjectIdChaptersChapterIdRoute: typeof ProjectsProjectIdChaptersChapterIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdLaunchRoute: ProjectsProjectIdLaunchRoute,
  ProjectsProjectIdChaptersChapterIdRoute:
    ProjectsProjectIdChaptersChapterIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  ScoutRoute: ScoutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
